# Generated by Django 2.2.17 on 2021-01-23 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_hour', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Order time')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_orders.Client')),
                ('pizzas', models.ManyToManyField(to='restaurant.Pizza')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
